### ISSUE TITLE
Right panel not showing details for attributes

### ISSUE THREAD

**Issue by Kirow** [Ahmed-Ali/RealmObjectEditor#9]
Just checked master branch and compiled app do not display details for attributes (i.e. can not set indexed/primary/ignored). Works for relations only.
same issue on v0.0.4

**Comment by akuzminskyi** [comment]
I fixed it by hidden some views, but I'm really not sure if its correct solution. 
EditorViewController.swift:

``` sh
    func selectedAttributeDidChange()
    {
        if selectedAttribute != nil{
            for subView in optionContainers{
                subView.hidden = true
            }
            attributeOptionsContainer.hidden = false
            populateAttributeUI()
        }
    }
```

**Comment by filip982** [comment]
Right panel still not working. This is cool helper program, it would be a bit waste not to fix this. Same thing like @Kirow reported.

**Comment by Ahmed-Ali** [comment]
Resolved by merging PR #12
